apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io/
    chart: authentik
    targetRevision: 2025.4.1
    helm:
      # Uses fix from here: https://github.com/goauthentik/authentik/discussions/12852#discussioncomment-13056628
      valuesObject:
        authentik:
          # This sends anonymous usage-data, stack traces on errors and
          # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
          error_reporting:
            enabled: false

        global:
          env:
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key

          ingress:
            annotations:
              cert-manager.io/cluster-issuer: lets-encrypt
              nginx.ingress.kubernetes.io/proxy-body-size: "0"

            # Specify kubernetes ingress controller class name
            ingressClassName: nginx
            enabled: true
            hosts:
              - authentik.jerryberry.nl

            tls:
              - hosts:
                  - authentik.jerryberry.nl
                secretName: authentik-tls

        postgresql:
          enabled: true
          auth:
            existingSecret: authentik-creds

        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
