apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goauthentik/helm
    targetRevision: authentik-2025.6.3
    path: charts/authentik
    helm:
      values: |
        authentik:
          secret_key: "PleaseGenerateA50CharKey"
          error_reporting:
            enabled: false
          postgresql:
            password: "ThisIsNotASecurePassword"

        server:
          ingress:
            enabled: true
            hosts:
              - authentik.domain.tld

        postgresql:
          enabled: true
          auth:
            password: "ThisIsNotASecurePassword"

        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


