---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-creds
  namespace: authentik
spec:
  encryptedData:
    password: AgCytEPzBdHT0VI19RoIK5wHmfT2ldzd345J5ed62+op20xI5SWI2SSEG3Edl7dZmvoi+j8NdHIgOON3wRfCT/9tVI3cmUozwSUuoHF4AJm3JiCI/nHa1XnIuJPlGXYXo+LI/Y2zkjG5i7djIbFPANokrgoELXgU7AC3R7ODlVTCzEBDcCFDubYDx/MG/hVDwRZ2T3jvIPaMcotL5U73R0Xon/kBLB2p+LYSZi+9OdCxZtNJUjR2YrvNdUnZusJRmxQgLO4bvwRrfRNvckck2ugz+NrMyGHihgsExNbhqXCcff/wyDiJGMflcqevq9Emr6OA67FkziXSpELqelfXNMi6hJhFtEwOJblxdkThQaPvisgdW+aZpA4izZfZxZWDn2AkHR/E1xagdwiN3llhWrZVEp+33ikOLmuErVQ/yq64yioYwFc5tsEZ5JBxaTKKnZBE1of4g4KDKVWZ2HjvJvOgE3LVTsh7eCgp0Q9Mw4zso1HiSGNxa72GtHINaTc0u8QzsI538oNTQKaHpGdv3WUshZ78/LcGX/bdlwNugwutWJuDy4K+WnUqHqFwEAUu6Lg8bFantzvOwOjzBk/rWDzArPO3oqNJtBOoVQ8goRRrPOKL1w2R1OpsZfCULRFX+HCuUuyaE5aHzjZxVv+JSdLYF9afXg+CL6cD2/xDqGMnE8cOP8f/g6vnDjkU1hu8deGe66ss+VAQ1QOCKJ85Q7ysx+2KV9Jm/WJ6XZM=
    postgres-password: AgCsZazwq0ZJGFqLJ93ogh15ovowK+9LqZnNTrY9hsZmrXLm/lxD4AGXTNdYY9AVnEEkDc9ebIg0lTfZBRC42lZsYq6dai6MIR97lGkfLS8HopcFVhuL+xPoBNUheS4dnnOVHSIC0foP9XbCbliX45irEDqng/zeSntNJ6GGhgKDoWE8nDsUcfvhgGVDWxDPqSRifE/uhgqpqe81JSRajIt/O5V9geBH/u2dRlsoPU6Umau7srLTM9m/qxzJaZp+oofRY/GWEwF3Fr62rdvLNTd88gXrYzXdwPhPVoNm/eI8634SO94CHEb611Opt032Ciz2qbQfwdh9DK83D/KrmjQ/q1gCPjWWpLn9pGnzOem3Z3w3F4fk1/6uwc78cmxL9msAsAEPjmcYzqiH3wgiPIS1atYaRpCaZ5K633oW58N0gi+2l1YWH41erSEMexcFkggb+61c2B2I0aE0VaBvts8lTUnVYSY2rGj1u+dAh+WtQNcwf6m1bqqK1z55gmfdisj5hdRnIgqhcBnGt4fQwZmccf3ZtAGwBMHX4bFSBV4EMMi2AO389NV3GLBadwHRHxYSRIPW97pilEizvOA91mdCW4Dr3AOT+xgXgdqEbg3QzP383cy48NanhwEY+SqYD0WTFtShj6whztByS32zBu1SNj9DYvyOyDB97iTVOV7KWO08/qVID5/QPaJu0/SFIbAVHAlXBaEa1J9lsJp82lZc4IY24BTkXsV/E/o=
    replication-password: AgAU1Erm4EiVqRbwcCYAp3jdAcYvvXdEL6jlFPPYNSbdRFMPOfzinrPlhFPGU76PFQarSqBd5MPVsd7sKaz99QAOkiMWAGpg8j0juO49qJqZYMUfvb8AcxfjPr/CY+m5fKM92ywpw/9uMfF2yWZySJO7OtyAmkrLVY2K4vksD6ca2kNuCKTMHzvVyRQwrBBjOKn3oNi/dUZ/k8XM6ivizPUqu0NEYUBWgba5lIIa1bsdCJUgzP0Hbirhm6ql0/EPW1hId5peZaINliuQVLZlGF9dcBQtNxcBRfIr6fF7k7jMRohPPOyWp9tuvN6w4qUSIjw4UnNirEMvWw/MFsUZZsmMqql6ANKFoMOajpWqFu2zTVJWqDAficz6nKrSsqmfEq1El1sfhbTq3T9e/bZVei3TCuE6bktIPH6MytJsPlmhtFm94c7KGRHcA+RaoIdNtHm0Zwx72poSiU5YDT0GhBDDdggja+7myH2vf0S/o6Zk04qA9IWym8e9qTqXESccZLX8InB2xQvlxW4m+RbHg+zMXwslHTzTs7xY51CDsxnWJjUq0O352yfXpoWgDFeFCQ/gdanaMrNacC8M46tvcmg2Zfqp7JnF+EbpS/6RpKGUVAAekEy3Z0LGQ8dmt/ZlvhRiPbtJpjCoXd/4cy4DCTUH7yvgca04a9dJW558C+vwUi3lUO6z1gZF7a9eH82aBDjv7s4tgTemj7lOZwSp+/a4ad/9suOfrY6LKXQ=
    secret_key: AgAOm4YnHAuYafhLbrFUPZGonCPM2MlH1GKbnn/ELMK32AQ1anFdoowTK3iPiNJQJ1muOWsdP/4fuESWOjWWONs3/kU8TlaENtUnY3fAgmt5Z4vKbPLeSq6QliWH98D+whf9q8DSXqWN4o09j4gq9PBR6ejZYFdqzuaQSJsL71EaA96Cn8oK2d+DUjwFhE8K0aIb/44iS6Q7E/c5UMg9LG9uZhPWf2nuiEgHk5RlbhvL4SSwdziLAyuJVXIW5UDxAklDFamwElzMcmKBqnZ45avF+j70qITkSh+7Ev6lPUcT/FOg/QKoflfUT3lfnYU7qu4ZJu0pjLYEO0jkiJ0IC3qMM9MkUeYE9c8N14i/TTSFqsgyGLz23J6eF3pgpq7CjWdEMJC4FRmqqeFGyVUqur8Zc0IMugoindqdPn7wu1bUKXSASgnPDBSxnaRjaUyRx+cxf81JjUlRromTBYzBmtOC3D+bnmeNkkyXoHkiaWDb1EB7AWhuVrM5yObGN6qJE25UMjtf410wntDc3Mk1Q26B1uWnmtevpvbr3e4mzM+qwqFWMaAdmZG2umrqfDwnTFFmzrJ+/SK5m9Yolod5N73fh5qZWQ0ROnF6VcoEhKX8KpTEu8842/dYH/iIH44/qFrWmAO3TWihVXNx+eGsC/36LjVdvgErng2PYUQHTvJgPNNCM1v6zzsloqLNRQ9zzmq5A9YQqMNaPYeGhto1Pco1XOele56WvgmH/MyiwgXSdTwlX36tNwZmsEaajjLb
  template:
    metadata:
      creationTimestamp: null
      name: authentik-creds
      namespace: authentik
    type: Opaque

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goauthentik/helm
    targetRevision: authentik-2025.6.3
    path: charts/authentik
    helm:
      values: |
        postgresql:
          enabled: true
          auth:
            existingSecret: authentik-creds
            secretKeys:
              adminPasswordKey: "password"
              userPasswordKey: "postgres-password"
              replicationPasswordKey: "replication-password"

        redis:
          enabled: true

        server:
          env:
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
          ingress:
            enabled: true
            hosts:
              - auth.jerryberry.nl

            tls:
            - hosts:
                - auth.jerryberry.nl
              secretName: n8n-tls

        worker:
          env:
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

