apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jellyfin/jellyfin-helm
    targetRevision: 2.3.0
    path: charts/jellyfin
    helm:
      values: |
        persistence:
          config:
            enabled: true
            storageClass: openebs-hostpath
            size: 10Gi
          media:
            enabled: true
            storageClass: manual
            size: 100Gi
            existingClaim: shared-media-pvc
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
