apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: jellyfin
    targetRevision: 4.5.2
    helm:
      values: |
        persistence:
          config:
            enabled: true
            storageClass: openebs-hostpath
            size: 10Gi
          media:
            enabled: true
            storageClass: openebs-hostpath
            size: 100Gi
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
