apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kumahq.github.io/charts
    chart: kuma
    targetRevision: 2.10.1
    helm:
      values: |
        controlPlane:
          mode: standalone
          tls:
            apiServer:
              create: true
          ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: lets-encrypt
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                nginx.ingress.kubernetes.io/backend-port: "5682"
              ingressClassName: nginx
              hostname: kuma.jerryberry.nl
              path: /
              pathType: Prefix
              servicePort: 5682
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
