apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kumahq/kuma
    path: deployments/charts/kuma
    targetRevision: 2.10.1
    helm:
      values: |
        controlPlane:
          mode: standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
