apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.5.0

    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: openebs-hostpath
                  resources:
                    requests:
                      storage: 2Gi
        kubeControllerManager:
          endpoints:
            - 192.168.1.11
        kubeScheduler:
          endpoints:
            - 192.168.1.11
        grafana:
          enabled: true
          adminPassword: prom-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

      # Added to resolve error that says CRD is invalid, annotation may not be more than 262144 bytes.
      - ServerSideApply=true
