# apps/n8n/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/8gears/n8n-helm-chart
    path: charts/n8n
    targetRevision: 1.0.6
    helm:
      values: |
        image:
          tag: latest
        n8n:
          host: n8n.jerryberry.nl
          protocol: https
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: n8n.jerryberry.nl
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - n8n.jerryberry.nl
              secretName: n8n-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
