# apps/n8n/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/8gears/n8n-helm-chart
    path: charts/n8n
    targetRevision: 1.0.6
    helm:
      values: |
        image:
          tag: latest
        main:
          config:
            N8N_HOST: "n8n.jerryberry.nl"
            N8N_PORT: "5678"
            N8N_PROTOCOL: "https"
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          enabled: true
          className: nginx
          hosts:
            - host: n8n.jerryberry.nl
              paths:
                - /
          tls:
            - hosts:
                - n8n.jerryberry.nl
              secretName: n8n-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
