apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    istio.io/dataplane-mode: ambient
