apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SonarSource/helm-chart-sonarqube
    targetRevision: HEAD
    path: charts/sonarqube
    helm:
      values: |
        edition: ""
        community:
          enabled: true
        monitoringPasscode: "some-secret-password-idk"
        persistence:
          enabled: true
          storageClass: openebs-hostpath
          size: 10G
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          enabled: true
          ingressClassName: nginx
          hosts:
            - name: sonarqube.jerryberry.nl
              path: /
          tls:
            - secretName: sonarqube-tls
              hosts:
                - sonarqube.jerryberry.nl
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
