apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: istio.io/rev
        operator: Exists
  podMetricsEndpoints:
    - port: envoy-prom
      path: /stats/prometheus
      interval: 15s
