apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-ztunnel
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - istio-cni
  selector:
    matchLabels:
      app: ztunnel
  podMetricsEndpoints:
    - port: http-envoy-prom
      interval: 15s
      path: /metrics
