apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-zztunnel
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: ztunnel
  podMetricsEndpoints:
    - port: "15020"
      interval: 15s
