---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-creds
  namespace: authentik
spec:
  encryptedData:
    password: AgCaOX70mZN939CWIYcehNKPxedxTpGR302E8jaZLg4/BHQ3isKoMcdjSejVAZ1BNmotSgWZJBXIFG2Qx4LljrG3r+bEEAJyeIiSSoKwOLwepiHB7ppyloqRKZ6OiUiFTnRk4bw/LWBNUk9tOTFtZGa0KmaKrztkOecG2k7U1Mo5kI0KiYC29cgR0S7HcfU4i7IQbXKrlCPt/rbxqfBVz7e8UbI8H9extFAaG4p/vD80XpU1FIhPCKBOE6Wz+83Q4mEZ+ebTatrImB/v3xoUOW4Q3wcS/Z1vh6tnU7KEmD297CV2O7uk6PtDTkat3tYp5/fCs5Yd+1t9MkpL/5D6PADWOtYaFsg6TuDyZoCtzUAyURTZKEV5VhxiEc1In6nrZ9L6xa4Acvaatsxr4YKo0WMuup5s4eQMUIkm9w2hJjMyHRqMfLtsp6GmsAGOC3qfxGBavuZCvi0Dh0nWOEqvapD5hRPmdJ6l0mu35+8UFddRK/Z/fZQmkjfhjuWy4vbhgamstaYVP9bzAK+wxR5Sm9NX/zSdxgldKfxeVNV7S4aOxPMbj4CVIp3E6CW7KQacnVjqEYQbsUe3OY6AqliKcuWElW0NNGKNYh8aAEhbDP1JG/FuVEeTMBAnjc6J9v/k/4Ot2rIzUVPMEBGHa6FT1pUwaqX3zQ8y6cFkyynw3tHEEHfposhEiY/stU9wCNzOT2sKvnvWjENfRxiSvQLtv6E=
    secret_key: AgCyN91EZCoB2rn9+Ix14UpwUEo1+4OejsBfvEZemSxq4cIIcAxpJsZQYo+sdSvQXvnlMYOc0XPxSLdLm219VpAuHbBbQyEtIbmBNruKuty1yBHJJpuJxW5tczFDiTCrOAOclHhNBIdI7J9iJpHcXPJYbGO41jmvR70X6pZKqvVndS4QAXSoU1soekDCFkJnlgLfKVW93r6Br5W6PembxhBM0u9lJi71vyHIiDDRRt2qejQ9CIyCneWH+gKC2K2i3Kc41Wb2/acSwpkrQPv2twxu5VHGgONI+MQLZcjq8LKuzltGY1eQpp1gh/9wI2v98v8ObvoY8QjPYfxuUtDOXBTnjOsc3W6NZOAgs+tfFW4Nl+oWqC5InA2qovTSu3oMdZNAdR65cxaAkf4m/E/XJGB6N7RbtndRHZG5gG6SpDvwucQkI6WzEYosJL8ewWS+BHaVrBSS53M1q34KCskmMqIV5Cc0pQj2ifFeFCuNx6QUhiTIB4pfGAcIgRBIXV0DapRyxKoeSMuXc2kcXt2Dm8ZNLaj9qrZSAReQE9bfXAS6WUBIXX+rlTXmhKmNGCRr9VUsCWk6ckBtC4QOATDCSQDzcyyezSLSL5SGQV3+jn7pX3AIuzGFW30FWcBmeHYkzSlD/XKC7ocKhWwNiA9SHjIoSCbXHKyRZspWIZIg2y8faibH0vO7DPUMOEzqhy4RHyeMCaHIKsx0ZUVkFB45hdwyWvnpJSoOUBORdH64dUq5XT8TpDBIdq9LZXR3itam1phgdA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-creds
      namespace: authentik
    type: Opaque
