apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/home/jerry/shared-media"
