apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-svc
  namespace: media
spec:
  selector:
    app: flaresolverr
  ports:
    - name: flaresolverr-port
      port: 8191
      targetPort: 8191
      protocol: TCP
  type: ClusterIP
