apiVersion: v1
kind: Service
metadata:
  name: prowlarr-svc
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
    - name: prowlarr-port
      port: 9696
      targetPort: 9696
      protocol: TCP
  type: ClusterIP
