apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: QBT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-credentials
                  key: username
            - name: QBT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-credentials
                  key: password
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: shared-media-pvc
