apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-svc
  namespace: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
