apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: koel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: koel-storage
              mountPath: /var/lib/mysql
              subPath: mariadb
      volumes:
        - name: koel-storage
          persistentVolumeClaim:
            claimName: koel-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koel
  namespace: koel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koel
  template:
    metadata:
      labels:
        app: koel
    spec:
      initContainers:
        - name: koel-init
          image: phanan/koel
          command: ["php", "artisan", "koel:init", "--no-assets"]
          env:
            - name: FORCE_HTTPS
              value: "true"
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              value: koel
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-password
          volumeMounts:
            - name: koel-storage
              mountPath: /music
              subPath: music
            - name: koel-storage
              mountPath: /var/www/html/public/img/covers
              subPath: covers
            - name: koel-storage
              mountPath: /var/www/html/storage/search-indexes
              subPath: search-indexes
      containers:
        - name: koel
          image: phanan/koel:latest
          ports:
            - containerPort: 80
          env:
            - name: FORCE_HTTPS
              value: "true"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: app-key
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koel-db-secret
                  key: mysql-password
          volumeMounts:
            - name: koel-storage
              mountPath: /music
              subPath: music
            - name: koel-storage
              mountPath: /var/www/html/public/img/covers
              subPath: covers
            - name: koel-storage
              mountPath: /var/www/html/storage/search-indexes
              subPath: search-indexes
      volumes:
        - name: koel-storage
          persistentVolumeClaim:
            claimName: koel-pvc
