apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-music-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/mnt/ssd/music-media"
