apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc
  namespace: koel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "manual"
  volumeName: ssd-music-pv
