apiVersion: v1
kind: Service
metadata:
  name: sonarr-svc
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
    - name: sonarr-port
      port: 8989
      targetPort: 8989
      protocol: TCP
  type: ClusterIP
