apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-nextcloud-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/mnt/ssd/nextcloud-media"
