apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: kiali-server
    repoURL: https://kiali.org/helm-charts
    targetRevision: 2.10.0
    helm:
      values: |
        auth:
          strategy: anonymous  # For local testing. Consider using login for prod.

        deployment:
          accessible_namespaces: ["**"]  # Adjust if you want to limit visibility
          ingress:
            enabled: false  # Set to true if using Ingress

        external_services:
          istio:
            url_service_version: http://istiod.istio-system:15014/version

          prometheus:
            url: http://kube-prom-stack-kube-prome-prometheus.observability.svc.cluster.local:9090

          grafana:
            enabled: true
            in_cluster_url: http://kube-prom-stack-grafana.observability.svc.cluster.local

          tracing:
            enabled: true
            in_cluster_url: http://tempo.observability.svc.cluster.local:16686

        istio_namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
