apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jerryberry-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - jerryberry.nl
        - docker.jerryberry.nl
        - movies.jerryberry.nl
        - chat.jerryberry.nl
        - sonarr.jerryberry.nl
        - transmission.jerryberry.nl
        - qbittorrent.jerryberry.nl
        - prowlarr.jerryberry.nl
        - argocd.jerryberry.nl
      secretName: jerryberry-ingress-tls
  rules:
    - host: jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-nodeport
                port:
                  number: 80
    - host: docker.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry
                port:
                  number: 5000
    - host: movies.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-ext
                port:
                  number: 8096
    - host: chat.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui-ext
                port:
                  number: 80
    - host: sonarr.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-ext
                port:
                  number: 8989
    - host: transmission.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission-ext
                port:
                  number: 9091
    - host: qbittorrent.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-ext
                port:
                  number: 8080
    - host: prowlarr.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr-ext
                port:
                  number: 9696
    - host: argocd.jerryberry.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-ext
                port:
                  number: 8080
