apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: koel
  name: database
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: mariadb
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          kuma.io/service: koel
      default:
        action: Allow
