apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  namespace: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: linuxserver/transmission:latest
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: transmission-config
              mountPath: /config
            - name: transmission-downloads
              mountPath: /downloads
      volumes:
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-pvc
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
      env:
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
