apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
