apiVersion: v1
kind: Service
metadata:
  name: radarr-svc
  namespace: media
spec:
  selector:
    app: radarr
  ports:
    - name: radarr-port
      port: 7878
      targetPort: 7878
      protocol: TCP
  type: ClusterIP
